[package]
name = "tf-integration-tests"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true
publish.workspace = true

[dependencies]
tf-core.workspace = true
tf-vision.workspace = true
tf-inference.workspace = true
tf-state.workspace = true
tf-rec.workspace = true
tf-table.workspace = true
tokio.workspace = true
parking_lot.workspace = true
